import type { TargetProfile } from '../../config/targets/types';

/**
 * saucedemo — the application under test is configuration, not code (§04).
 *
 * Generated by `npm run target:new`. Every value below is a claim about the
 * application: set them to what is *true*, not to what you would like. A
 * capability declared on but absent fails obscurely; one declared off is
 * reported as "not applicable" rather than as a silent zero.
 *
 * `npm run target:doctor` checks this file against the pack and the secret
 * store, and names the file to fix for anything that disagrees.
 */
export const saucedemo: TargetProfile = {
  name: 'saucedemo',

  // Environment values come from the pipeline where there is one, so a profile
  // never ships a host someone can accidentally point at production.
  baseURL: process.env.BASE_URL ?? 'https://www.saucedemo.com',
  environment: process.env.TARGET_ENV ?? 'staging',

  credentials: {
    source: (process.env.SECRET_SOURCE as 'vault' | 'local') ?? 'local',
    root: 'qa/saucedemo/pools',
    accountType: 'workforce',
  },

  capabilities: {
    mfa: 'none', // 'none' | 'totp' | 'email'
    accountPool: 'static', // 'static' | 'leased'
    /*
       Yes — data this suite creates is cleaned up after itself.

       Kept true rather than examined: this application's cart lives in the
       browser, so the claim is thin, but `serverState` also governs cleanup
       expectations and narrowing it was not what item 67 measured.
    */
    serverState: true,
    /*
       Yes, measured — item 67, 2026-08-23.

       `npm run pool:measure --target=saucedemo --runs=5`: **5/5 green at the
       ceiling of 1, and 5/5 green above it with every worker on this one
       account.** A further 2 runs at six workers were green as well.

       Without this the suite ran serially, because `workerCeiling` reads
       `serverState` and one account caps it at a single worker. Nothing here
       is per-identity on the server, so there was nothing for the cap to
       protect.
    */
    sharedIdentitySafe: true,
    api: { enabled: false, baseURL: process.env.API_BASE_URL },
    db: { enabled: false, vaultRole: 'qa-readonly', dialect: 'postgres' },
    // Off until the published document is vendored to the path below.
    contracts: { enabled: false, spec: null },
    a11y: {
      enabled: false,
      standard: process.env.A11Y_STANDARD ?? 'wcag22aa',
    },
  },

  // Which attribute `getByTestId` reads. Applications disagree — data-test,
  // data-testid, data-qa — and it is a property of the app, not the framework.
  testIdAttribute: process.env.TEST_ID_ATTRIBUTE ?? 'data-test',

  // Hosts this profile may drive. Generation and exploration run against test
  // environments only, enforced here rather than by convention (§17).
  hostAllowlist: ['saucedemo.com'],

  suites: ['smoke', 'regression'],

  // The first role is the default identity for `authedPage`.
  roles: ['standard'],
};
