/**
 * Stored sessions that belong to nothing — §11, §19.
 *
 * A storage state is a live credential. It is gitignored, it is regenerated by
 * `setup:auth` on every run, and `target:remove` shreds the ones belonging to
 * the target it is removing.
 *
 * What nothing did was notice the ones belonging to a target that is *gone*.
 * They arrive easily enough — a target removed by hand, a rename, a scaffold
 * abandoned halfway, a branch switched underneath a `.auth/` that is not in
 * git — and once there, nothing ever looks at them again. Two were found in
 * this repository for applications it had not known about for weeks.
 *
 * A dormant session for an application nobody is testing is the worst kind of
 * credential: still valid, still on disk, and attached to no reason for
 * anybody to think about it.
 */

/** A session file, split into what it says about itself. */
export interface StoredSession {
  /** The file, as it sits in `.auth/`. */
  file: string;
  target: string;
  role: string;
}

/**
 * Read `<target>.<role>.json` back into its two halves.
 *
 * Returns null for anything that is not that shape. `.auth/` is gitignored and
 * therefore a place people put things — a scratch file there must not be
 * reported as an orphaned credential, and must certainly never be offered up
 * for deletion.
 *
 * Target names cannot contain a dot (`NAME_PATTERN` in the scaffolder allows
 * lower-case words joined by hyphens), so the first dot is the boundary and
 * there is no ambiguity to resolve.
 */
export function parseSessionFile(file: string): StoredSession | null {
  const match = /^([a-z][a-z0-9]*(?:-[a-z0-9]+)*)\.([^.]+)\.json$/.exec(file);
  if (!match?.[1] || !match[2]) return null;
  return { file, target: match[1], role: match[2] };
}

/**
 * Sessions whose target is not onboarded any more.
 *
 * Anything unparseable is left alone rather than guessed at, for the reason
 * above: this list is what a tool offers to delete.
 */
export function orphanedSessions(
  storageStateFiles: readonly string[],
  knownTargets: readonly string[],
): StoredSession[] {
  const known = new Set(knownTargets);
  return storageStateFiles
    .map(parseSessionFile)
    .filter((session): session is StoredSession => session !== null && !known.has(session.target));
}

/** One line saying what was found and what to do about it. */
export function describeOrphanedSessions(sessions: readonly StoredSession[]): string {
  const names = sessions.map((session) => session.file);
  return (
    `${names.length} stored session(s) belong to no application in this repository: ` +
    `${names.slice(0, 4).join(', ')}${names.length > 4 ? ` and ${names.length - 4} more` : ''}. ` +
    'A storage state is a live credential, so one left behind by a removed or renamed target is ' +
    'a login nobody is tracking. Delete them — `setup:auth` writes a fresh one per run, so ' +
    'nothing is lost.'
  );
}
