import type { TargetProfile } from './types';

/**
 * orangehrm — the application under test is configuration, not code (§04).
 *
 * Generated by `npm run target:new`. Every value below is a claim about the
 * application: set them to what is *true*, not to what you would like. A
 * capability declared on but absent fails obscurely; one declared off is
 * reported as "not applicable" rather than as a silent zero.
 *
 * `npm run target:doctor` checks this file against the pack and the secret
 * store, and names the file to fix for anything that disagrees.
 */
export const orangehrm: TargetProfile = {
  name: 'orangehrm',

  // Environment values come from the pipeline where there is one, so a profile
  // never ships a host someone can accidentally point at production.
  baseURL: process.env.BASE_URL ?? 'https://opensource-demo.orangehrmlive.com',
  environment: process.env.TARGET_ENV ?? 'staging',

  credentials: {
    source: (process.env.SECRET_SOURCE as 'vault' | 'local') ?? 'local',
    root: 'qa/orangehrm/pools',
    accountType: 'workforce',
  },

  capabilities: {
    mfa: 'none', // 'none' | 'totp' | 'email'
    accountPool: 'static', // 'static' | 'leased'
    /*
       Yes, and it is real here — these specs add and remove system users, and
       a leaked one is visible to every later run.
    */
    serverState: true,
    /*
       **No — the cap is earned.** Item 67, 2026-08-23, and this one was set and
       reverted the same day.

       `npm run pool:measure --runs=5` reported 5/5 green at the ceiling of 1
       and 5/5 green above it, so the flag went on. But that measurement ran at
       **two** workers, and lifting the cap runs this suite at whatever
       Playwright picks locally — five, here.

       At five workers: **4 of 5 runs green, and the fifth failed OHRM-3-01 · a
       user that was added is on the list, and gone once removed.** That is the
       `@audit` spec, and the failure is a *list* that another worker was
       mutating underneath it.

       The users this suite creates are global rather than owned by the
       administrator signing in, so concurrent workers see each other's records
       appear and disappear. Sharing the identity was never the hazard; sharing
       the user list is.

       `restful-booker` reverted the same day for the identical reason on its
       room list, which is what makes this a shape rather than a coincidence.
    */
    // sharedIdentitySafe: intentionally unset — see above.
    api: { enabled: false, baseURL: process.env.API_BASE_URL },
    db: { enabled: false, vaultRole: 'qa-readonly', dialect: 'postgres' },
    // Off until the published document is vendored to the path below.
    contracts: { enabled: false, spec: null },
    a11y: {
      enabled: true,
      standard: process.env.A11Y_STANDARD ?? 'wcag22aa',
      /*
         Measured on 2026-08-18, not assumed: the sign-in page fails
         html-has-lang on one node. That is the vendor's defect on a demo this
         repository does not own and cannot fix, so it is recorded as a waiver
         with a reason and a review date — which is what the conventions ask
         for — rather than by deleting the assertion.

         Scoped to the sign-in page on purpose. A bare rule id would suppress
         it everywhere, and the point of scanning this application is that its
         other pages get scanned honestly. The scan still counts waived nodes,
         so an exception accepted for one cannot quietly become ninety.
      */
      waived: [
        {
          rule: 'html-has-lang',
          reason:
            'Vendor demo: the document declares no language. Not ours to fix, and the page is ' +
            'kept in the suite because it is the first thing an administrator sees.',
          reviewBy: '2026-11-18',
          // The dashboard, not the sign-in page: authedPage is signed in, so
          // '/' redirects there. Scoped from the URL the scan reported rather
          // than the one the page was assumed to be.
          urlPattern: 'dashboard/index',
        },
      ],
    },
  },

  // Which attribute `getByTestId` reads. Applications disagree — data-test,
  // data-testid, data-qa — and it is a property of the app, not the framework.
  testIdAttribute: process.env.TEST_ID_ATTRIBUTE ?? 'data-testid',

  // Hosts this profile may drive. Generation and exploration run against test
  // environments only, enforced here rather than by convention (§17).
  hostAllowlist: ['orangehrmlive.com'],

  suites: ['smoke', 'regression'],

  // The first role is the default identity for `authedPage`.
  roles: ['admin'],
};
