import type { TargetProfile } from './types';

/**
 * parabank — the application under test is configuration, not code (§04).
 *
 * Generated by `npm run target:new`. Every value below is a claim about the
 * application: set them to what is *true*, not to what you would like. A
 * capability declared on but absent fails obscurely; one declared off is
 * reported as "not applicable" rather than as a silent zero.
 *
 * `npm run target:doctor` checks this file against the pack and the secret
 * store, and names the file to fix for anything that disagrees.
 */
export const parabank: TargetProfile = {
  name: 'parabank',

  // Environment values come from the pipeline where there is one, so a profile
  // never ships a host someone can accidentally point at production.
  baseURL: process.env.BASE_URL ?? 'https://parabank.parasoft.com',
  environment: process.env.TARGET_ENV ?? 'staging',

  credentials: {
    /*
       `local` is legitimate here for the same reason it is on the other two
       demos: `john`/`demo` is printed on ParaBank's own login page. It still
       resolves through the `secrets` fixture — the moment one target bypasses
       it, the lint rule stops being enforceable.
    */
    source: (process.env.SECRET_SOURCE as 'vault' | 'local') ?? 'local',
    root: 'qa/parabank/pools',
    accountType: 'workforce',
  },

  /*
     Shared with everybody else on the internet, and it shows: `john`'s balances
     move while a run is in flight, because strangers are transferring money
     between the same accounts. Two consequences, both load-bearing for the
     specs:

       - every balance assertion is *relative* — read, act, read again — and
         never an absolute figure;
       - anything asserted about is opened or transferred by the spec that
         asserts it, per "never assert on data the spec did not create".

     Also, measured on 2026-08-18: the host returned Cloudflare 502s for about
     forty seconds in a sixty-second window, then recovered and stayed up for
     twelve consecutive probes. Failures here are as likely to be the
     deployment as the suite, which is what the `network-infrastructure` triage
     category exists to say.
  */
  sharedEnvironment: true,

  /*
     Parked on 2026-08-19, at the owner's direction, and the reason is the
     application rather than the suite.

     ParaBank's own login and accounts endpoints answered **HTTP 500** twice in
     one day — checked directly against the service, not inferred from a
     failure — so every spec here fails at the first page. Triage settles all
     five as `application-defect` via the `server-error` rule, which is correct
     and is exactly the point: nothing in this repository can fix it, and a red
     that nobody can act on costs the signal on the four applications that can.

     The specs stay. Two of them (PB-2-01, PB-6-01) report real defects — this
     bank accepts a negative transfer and one larger than the account holds —
     and deleting them to get a green board is the trade the conventions refuse.

     `npm run suites:live -- --target=parabank` still runs it, which is how to
     find out whether the reason still holds.
  */
  parked: {
    reason: 'ParaBank answers HTTP 500 on its own login and accounts pages',
    reviewBy: '2026-09-19',
  },

  capabilities: {
    mfa: 'none', // 'none' | 'totp' | 'email'
    accountPool: 'static', // 'static' | 'leased'
    serverState: true, // does state need cross-test cleanup?
    api: {
      enabled: true,
      baseURL: process.env.API_BASE_URL ?? 'https://parabank.parasoft.com/parabank/services/bank',
    },
    db: { enabled: false, vaultRole: 'qa-readonly', dialect: 'postgres' },
    // Off until the published document is vendored to the path below.
    contracts: { enabled: false, spec: null },
    a11y: {
      enabled: true,
      standard: process.env.A11Y_STANDARD ?? 'wcag22aa',
      /*
         Measured on 2026-08-18, not assumed: the landing page fails with one
         critical and four serious rules. These are the vendor's defects on a
         demo this repository does not own and cannot fix, so they are recorded
         as waivers with a reason and a review date — which is what the
         conventions ask for — rather than by deleting the assertion.

         Scoped to the landing page on purpose. A bare rule id would suppress
         these everywhere, and the whole point of onboarding this application is
         that its *other* pages get scanned honestly. The scan still counts
         waived nodes, so an exception accepted for one image cannot quietly
         become ninety.
      */
      waived: [
        {
          rule: 'image-alt',
          reason:
            "Vendor demo: the masthead logo image has no alt text. Not ours to fix, and " +
            'the page is kept in the suite because the sign-in form on it is what specs use.',
          reviewBy: '2026-11-18',
          urlPattern: 'parabank/index.htm',
        },
        {
          rule: 'color-contrast',
          reason: 'Vendor demo: six nodes in the marketing panels fall below 4.5:1.',
          reviewBy: '2026-11-18',
          urlPattern: 'parabank/index.htm',
        },
        {
          rule: 'html-has-lang',
          reason: 'Vendor demo: the document declares no language.',
          reviewBy: '2026-11-18',
          urlPattern: 'parabank/index.htm',
        },
        {
          rule: 'link-name',
          reason: 'Vendor demo: the masthead logo link has no accessible name.',
          reviewBy: '2026-11-18',
          urlPattern: 'parabank/index.htm',
        },
        {
          rule: 'target-size',
          reason:
            'Vendor demo: fifteen footer and nav links are below the 24×24 minimum ' +
            'WCAG 2.2 added. Waived at the standard this profile declares, not below it.',
          reviewBy: '2026-11-18',
          urlPattern: 'parabank/index.htm',
        },
      ],
    },
  },

  /*
     Stated, and unused. Read off the running application: ParaBank carries no
     `data-test`, `data-testid`, `data-qa` or `data-cy` attribute anywhere —
     nought occurrences on the sign-in page. It is a JSP application that
     predates the convention, so every locator in this pack resolves by role,
     by text, or by CSS with the justification the rule requires. The value
     below is the framework's default rather than a claim about this
     application.
  */
  testIdAttribute: process.env.TEST_ID_ATTRIBUTE ?? 'data-testid',

  // Hosts this profile may drive. Generation and exploration run against test
  // environments only, enforced here rather than by convention (§17).
  hostAllowlist: ['parasoft.com'],

  suites: ['smoke', 'regression'],

  // The first role is the default identity for `authedPage`.
  roles: ['customer'],
};
