import type { TargetProfile } from './types';

/**
 * toolshop — the application under test is configuration, not code (§04).
 *
 * Generated by `npm run target:new`. Every value below is a claim about the
 * application: set them to what is *true*, not to what you would like. A
 * capability declared on but absent fails obscurely; one declared off is
 * reported as "not applicable" rather than as a silent zero.
 *
 * `npm run target:doctor` checks this file against the pack and the secret
 * store, and names the file to fix for anything that disagrees.
 */
export const toolshop: TargetProfile = {
  name: 'toolshop',

  // Environment values come from the pipeline where there is one, so a profile
  // never ships a host someone can accidentally point at production.
  baseURL: process.env.BASE_URL ?? 'https://practicesoftwaretesting.com',
  environment: process.env.TARGET_ENV ?? 'staging',

  credentials: {
    source: (process.env.SECRET_SOURCE as 'vault' | 'local') ?? 'local',
    root: 'qa/toolshop/pools',
    accountType: 'workforce',
  },

  capabilities: {
    mfa: 'none', // 'none' | 'totp' | 'email'
    accountPool: 'static', // 'static' | 'leased'
    /*
       True, and it is the fact that shapes every spec here. The cart lives on
       the server against the signed-in account, and the account pool is
       static — so two workers signing in as `customer` share one cart. Every
       cart spec empties what it added rather than assuming it owns the account.
    */
    serverState: true,
    api: {
      enabled: true,
      baseURL: process.env.API_BASE_URL ?? 'https://api.practicesoftwaretesting.com',
    },
    db: { enabled: false, vaultRole: 'qa-readonly', dialect: 'postgres' },
    /*
       On, because the document is vendored rather than "available". Toolshop
       publishes OpenAPI 3.2.0 at https://api.practicesoftwaretesting.com/docs
       ?api-docs.json — a URL shaped exactly like the one `checkApiBaseURL`
       warns about, which is why the base URL above is the origin and this is
       the document.
    */
    contracts: { enabled: true, spec: 'src/targets/toolshop/contracts/openapi.json' },
    a11y: {
      enabled: true,
      standard: process.env.A11Y_STANDARD ?? 'wcag22aa',
    },
  },

  // Which attribute `getByTestId` reads. Applications disagree — data-test,
  // data-testid, data-qa — and it is a property of the app, not the framework.
  testIdAttribute: process.env.TEST_ID_ATTRIBUTE ?? 'data-test',

  // Hosts this profile may drive. Generation and exploration run against test
  // environments only, enforced here rather than by convention (§17).
  hostAllowlist: ['practicesoftwaretesting.com'],

  suites: ['smoke', 'regression'],

  // The first role is the default identity for `authedPage`.
  roles: ['customer', 'admin'],
};
