import type { TargetProfile } from './types';

/**
 * toolshop — the application under test is configuration, not code (§04).
 *
 * Generated by `npm run target:new`. Every value below is a claim about the
 * application: set them to what is *true*, not to what you would like. A
 * capability declared on but absent fails obscurely; one declared off is
 * reported as "not applicable" rather than as a silent zero.
 *
 * `npm run target:doctor` checks this file against the pack and the secret
 * store, and names the file to fix for anything that disagrees.
 */
export const toolshop: TargetProfile = {
  name: 'toolshop',

  // Environment values come from the pipeline where there is one, so a profile
  // never ships a host someone can accidentally point at production.
  baseURL: process.env.BASE_URL ?? 'https://practicesoftwaretesting.com',
  environment: process.env.TARGET_ENV ?? 'staging',

  credentials: {
    /*
       `local` is legitimate here and almost nowhere else: these credentials
       are published by the vendor in their own README, on a demo everybody
       shares. They still resolve through the `secrets` fixture — the moment
       one target bypasses it, the lint rule stops being enforceable.
    */
    source: (process.env.SECRET_SOURCE as 'vault' | 'local') ?? 'local',
    root: 'qa/toolshop/pools',
    accountType: 'workforce',

    /*
       Three customer accounts, so three workers get a cart each.

       Toolshop's cart is server-side against the signed-in account. With one
       account the cart specs had to run serially or empty each other's carts
       mid-assertion; with a pool they are partitioned by worker and run in
       parallel again. The admin role has one account and does not need more —
       nothing here writes as the admin.

       Taken from the vendor's published account table and checked against the
       live login endpoint before being written down. `customer3` has a
       different password from the other two, which is exactly the sort of
       detail a transcribed-from-memory pool gets wrong.
    */
    poolSize: { customer: 3, admin: 1 },

    /*
       `customer3` is reserved for the signed-out `auth-flows` project, so the
       specs that drive the login form never share an identity with the cart
       specs running beside them.

       They did, deterministically, and it is what made this suite
       intermittently red: `auth-flows` has no `dependencies` so it runs
       alongside `e2e`, and `secrets.account('customer')` defaults to index 1
       — the same account `e2e`'s slot-0 worker holds while it is adding and
       removing products. Observed as a search whose listing never changed and
       a cart row that would not detach, both passing in isolation.

       This costs a worker: `e2e` now runs at two rather than three, because
       the ceiling is what the pool has left. Three workers with a guaranteed
       collision is worse than two without one.
    */
    authFlowAccount: 3,
  },

  /*
       Shared with everybody else using the demo, so the tests that are
       destructive to the *environment* are off: this application locks an
       account after three consecutive failures (HTTP 423) and only an
       administrator can unlock it. A negative-authentication spec run here
       would spend somebody else's next test run.
  */
  sharedEnvironment: true,

  capabilities: {
    mfa: 'none', // 'none' | 'totp' | 'email'
    accountPool: 'static', // 'static' | 'leased'
    /*
       True, and it is the fact that shapes every spec here. The cart lives on
       the server against the signed-in account, and the account pool is
       static — so two workers signing in as `customer` share one cart. Every
       cart spec empties what it added rather than assuming it owns the account.
    */
    serverState: true,
    api: {
      enabled: true,
      baseURL: process.env.API_BASE_URL ?? 'https://api.practicesoftwaretesting.com',
    },
    db: { enabled: false, vaultRole: 'qa-readonly', dialect: 'postgres' },
    /*
       On, because the document is vendored rather than "available". Toolshop
       publishes OpenAPI 3.2.0 at https://api.practicesoftwaretesting.com/docs
       ?api-docs.json — a URL shaped exactly like the one `checkApiBaseURL`
       warns about, which is why the base URL above is the origin and this is
       the document.
    */
    contracts: {
      enabled: true,
      spec: 'src/targets/toolshop/contracts/openapi.json',
      /*
         Measured on 2026-08-18, both sides read rather than inferred:

           document  components.schemas.PaginatedProductResponse types `from`
                     and `to` as { type: 'integer' }, not nullable.
           service   GET /products/search?q=<no matches> answers
                     {"current_page":1,"data":[],"from":null,"to":null,"total":0}

         So the published document does not describe the service's own
         empty-result answer. Every populated search validates; only the empty
         one does not, which is why the contract suite gives that case its own
         spec.

         This is the vendor's demo and the vendor's document — neither side is
         ours to fix — so it is recorded here with a reason and a review date
         rather than by deleting the spec. Scoped to the two properties on the
         one endpoint: everything else about a search response is still
         checked, and the scan still counts what it waives.
      */
      waived: [
        {
          endpoint: 'GET /products/search',
          at: '/from',
          reason:
            "Vendor demo: the paginated envelope's `from` is null on an empty result set, " +
            'where the published document types it as a plain integer.',
          reviewBy: '2026-11-18',
        },
        {
          endpoint: 'GET /products/search',
          at: '/to',
          reason:
            "Vendor demo: the paginated envelope's `to` is null on an empty result set, " +
            'where the published document types it as a plain integer.',
          reviewBy: '2026-11-18',
        },
      ],
    },
    a11y: {
      enabled: true,
      standard: process.env.A11Y_STANDARD ?? 'wcag22aa',
    },
  },

  // Which attribute `getByTestId` reads. Applications disagree — data-test,
  // data-testid, data-qa — and it is a property of the app, not the framework.
  testIdAttribute: process.env.TEST_ID_ATTRIBUTE ?? 'data-test',

  // Hosts this profile may drive. Generation and exploration run against test
  // environments only, enforced here rather than by convention (§17).
  hostAllowlist: ['practicesoftwaretesting.com'],

  suites: ['smoke', 'regression'],

  // The first role is the default identity for `authedPage`.
  roles: ['customer', 'admin'],
};
